/*******************************************************************************
 * Copyright (c) 2025 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.solr.client.embedded;

import static org.hamcrest.CoreMatchers.containsString;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.junit.Assert.assertThrows;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

public class FactoryTest {

	private String originalSolrHome;

	@Before
	public void setUp() {
		originalSolrHome = System.getProperty("solr.solr.home");
		System.clearProperty("solr.solr.home");
	}

	@After
	public void tearDown() {
		if (originalSolrHome == null) {
			System.clearProperty("solr.solr.home");
		} else {
			System.setProperty("solr.solr.home", originalSolrHome);
		}
	}

	@Test
	public void embeddedSolrRequiresConfiguredHome() {
		Factory factory = new Factory();

		IllegalStateException exception = assertThrows(IllegalStateException.class,
				() -> factory.create("embedded:"));

		assertThat(exception.getMessage(), containsString("solr.solr.home"));
	}
}
