/*******************************************************************************
 * Copyright (c) 2025 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.EOFException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;

import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.Statement;
import org.eclipse.rdf4j.rio.RDFFormat;
import org.eclipse.rdf4j.rio.RDFHandlerException;
import org.eclipse.rdf4j.rio.RDFParseException;
import org.eclipse.rdf4j.rio.RDFParser;
import org.eclipse.rdf4j.rio.Rio;
import org.eclipse.rdf4j.rio.helpers.AbstractRDFHandler;
import org.eclipse.rdf4j.sail.SailException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

class LmdbBulkLoader {

	private static final Logger logger = LoggerFactory.getLogger(LmdbBulkLoader.class);

	private static final int DEFAULT_BUCKET_COUNT = 256;
	private static final int RECORD_LONGS = 4;
	private static final int RECORD_BYTES = RECORD_LONGS * Long.BYTES;

	private final Path dataDir;
	private final ValueStore valueStore;
	private final TripleStore tripleStore;
	private final int bucketCount;

	LmdbBulkLoader(Path dataDir, ValueStore valueStore, TripleStore tripleStore) {
		this(dataDir, valueStore, tripleStore, DEFAULT_BUCKET_COUNT);
	}

	LmdbBulkLoader(Path dataDir, ValueStore valueStore, TripleStore tripleStore, int bucketCount) {
		this.dataDir = Objects.requireNonNull(dataDir, "dataDir must not be null");
		this.valueStore = Objects.requireNonNull(valueStore, "valueStore must not be null");
		this.tripleStore = Objects.requireNonNull(tripleStore, "tripleStore must not be null");
		if (bucketCount <= 0) {
			throw new IllegalArgumentException("bucketCount must be positive");
		}
		this.bucketCount = bucketCount;
	}

	void bulkLoad(Path dataFile, RDFFormat format) throws SailException {
		Objects.requireNonNull(dataFile, "dataFile must not be null");
		Objects.requireNonNull(format, "format must not be null");

		Path workDir = null;
		boolean success = false;
		try {
			workDir = Files.createTempDirectory(dataDir, "bulk-load-");
			Path quadFile = workDir.resolve("quads.bin");
			BulkStats stats = writeQuadIdFile(dataFile, format, quadFile);
			List<String> indexFieldSequences = tripleStore.getIndexFieldSequences();
			boolean updateContexts = true;
			for (String fieldSeq : indexFieldSequences) {
				List<Path> bucketFiles = bucketQuads(quadFile, workDir, fieldSeq, stats);
				Comparator<long[]> comparator = comparatorFor(fieldSeq);
				TripleStore.BulkIndexWriter writer = tripleStore.beginBulkLoad(fieldSeq, true, updateContexts);
				try {
					for (Path bucketFile : bucketFiles) {
						long[][] quads = readBucket(bucketFile);
						Arrays.sort(quads, comparator);
						for (long[] quad : quads) {
							writer.append(quad);
						}
					}
					writer.close();
				} catch (Exception e) {
					try {
						writer.abort();
					} catch (IOException abortException) {
						logger.warn("Failed to abort bulk load for index {}", fieldSeq, abortException);
					}
					throw e;
				}
				updateContexts = false;
				cleanupFiles(bucketFiles);
			}
			success = true;
		} catch (IOException | RDFParseException | RDFHandlerException e) {
			throw new SailException("Bulk load failed", e);
		} finally {
			if (success && workDir != null) {
				try {
					deleteRecursively(workDir);
				} catch (IOException e) {
					logger.warn("Failed to delete bulk load temporary files in {}", workDir, e);
				}
			}
		}
	}

	private BulkStats writeQuadIdFile(Path dataFile, RDFFormat format, Path quadFile)
			throws IOException, RDFParseException, RDFHandlerException {
		BulkStats stats = new BulkStats();
		valueStore.startTransaction(true);
		try (InputStream in = new BufferedInputStream(Files.newInputStream(dataFile));
				DataOutputStream out = new DataOutputStream(
						new BufferedOutputStream(Files.newOutputStream(quadFile)))) {
			RDFParser parser = Rio.createParser(format);
			parser.setRDFHandler(new IdWritingHandler(out, stats));
			parser.parse(in, dataFile.toUri().toString());
			out.flush();
			valueStore.commit();
			return stats;
		} catch (IOException | RDFParseException | RDFHandlerException e) {
			valueStore.rollback();
			throw e;
		}
	}

	private List<Path> bucketQuads(Path quadFile, Path workDir, String fieldSeq, BulkStats stats) throws IOException {
		long maxValue = stats.maxForField(fieldSeq.charAt(0));
		List<Path> buckets = new ArrayList<>(bucketCount);
		DataOutputStream[] outputs = new DataOutputStream[bucketCount];
		for (int i = 0; i < bucketCount; i++) {
			buckets.add(workDir.resolve(fieldSeq + "-bucket-" + i + ".bin"));
		}
		try (DataInputStream in = new DataInputStream(new BufferedInputStream(Files.newInputStream(quadFile)))) {
			while (true) {
				long[] quad = readQuad(in);
				int bucket = bucketFor(firstComponent(quad, fieldSeq), maxValue);
				DataOutputStream out = outputs[bucket];
				if (out == null) {
					out = new DataOutputStream(new BufferedOutputStream(Files.newOutputStream(buckets.get(bucket))));
					outputs[bucket] = out;
				}
				writeQuad(out, quad);
			}
		} catch (EOFException ignored) {
			// finished
		} finally {
			for (DataOutputStream out : outputs) {
				if (out != null) {
					out.close();
				}
			}
		}
		return buckets;
	}

	private long[][] readBucket(Path bucketFile) throws IOException {
		if (!Files.exists(bucketFile)) {
			return new long[0][0];
		}
		long size = Files.size(bucketFile);
		if (size == 0) {
			return new long[0][0];
		}
		long count = size / RECORD_BYTES;
		if (count > Integer.MAX_VALUE) {
			throw new IOException("Bucket too large to sort in memory: " + bucketFile);
		}
		long[][] quads = new long[(int) count][RECORD_LONGS];
		try (DataInputStream in = new DataInputStream(new BufferedInputStream(Files.newInputStream(bucketFile)))) {
			for (int i = 0; i < count; i++) {
				quads[i] = readQuad(in);
			}
		}
		return quads;
	}

	private int bucketFor(long value, long maxValue) {
		if (maxValue <= 0) {
			return 0;
		}
		double fraction = (double) value / (double) (maxValue + 1);
		int bucket = (int) (fraction * bucketCount);
		return Math.min(bucketCount - 1, Math.max(0, bucket));
	}

	private long firstComponent(long[] quad, String fieldSeq) {
		switch (fieldSeq.charAt(0)) {
		case 's':
			return quad[TripleStore.SUBJ_IDX];
		case 'p':
			return quad[TripleStore.PRED_IDX];
		case 'o':
			return quad[TripleStore.OBJ_IDX];
		case 'c':
			return quad[TripleStore.CONTEXT_IDX];
		default:
			throw new IllegalArgumentException("Unsupported index field sequence: " + fieldSeq);
		}
	}

	private Comparator<long[]> comparatorFor(String fieldSeq) {
		int[] order = orderFor(fieldSeq);
		return (left, right) -> {
			for (int idx : order) {
				int cmp = Long.compare(left[idx], right[idx]);
				if (cmp != 0) {
					return cmp;
				}
			}
			return 0;
		};
	}

	private int[] orderFor(String fieldSeq) {
		int[] order = new int[fieldSeq.length()];
		for (int i = 0; i < fieldSeq.length(); i++) {
			switch (fieldSeq.charAt(i)) {
			case 's':
				order[i] = TripleStore.SUBJ_IDX;
				break;
			case 'p':
				order[i] = TripleStore.PRED_IDX;
				break;
			case 'o':
				order[i] = TripleStore.OBJ_IDX;
				break;
			case 'c':
				order[i] = TripleStore.CONTEXT_IDX;
				break;
			default:
				throw new IllegalArgumentException("Unsupported index field sequence: " + fieldSeq);
			}
		}
		return order;
	}

	private long[] readQuad(DataInputStream in) throws IOException {
		return new long[] { in.readLong(), in.readLong(), in.readLong(), in.readLong() };
	}

	private void writeQuad(DataOutputStream out, long[] quad) throws IOException {
		out.writeLong(quad[0]);
		out.writeLong(quad[1]);
		out.writeLong(quad[2]);
		out.writeLong(quad[3]);
	}

	private void cleanupFiles(List<Path> bucketFiles) {
		for (Path bucketFile : bucketFiles) {
			if (bucketFile != null) {
				try {
					Files.deleteIfExists(bucketFile);
				} catch (IOException e) {
					logger.debug("Failed to delete bucket file {}", bucketFile, e);
				}
			}
		}
	}

	private void deleteRecursively(Path root) throws IOException {
		if (!Files.exists(root)) {
			return;
		}
		try (var paths = Files.walk(root)) {
			paths.sorted((left, right) -> right.compareTo(left)).forEach(path -> {
				try {
					Files.deleteIfExists(path);
				} catch (IOException e) {
					throw new RuntimeException(e);
				}
			});
		} catch (RuntimeException e) {
			if (e.getCause() instanceof IOException) {
				throw (IOException) e.getCause();
			}
			throw e;
		}
	}

	private final class IdWritingHandler extends AbstractRDFHandler {

		private final DataOutputStream out;
		private final BulkStats stats;

		private IdWritingHandler(DataOutputStream out, BulkStats stats) {
			this.out = out;
			this.stats = stats;
		}

		@Override
		public void handleStatement(Statement statement) throws RDFHandlerException {
			try {
				long subjId = valueStore.storeValue(statement.getSubject());
				long predId = valueStore.storeValue(statement.getPredicate());
				long objId = valueStore.storeValue(statement.getObject());
				Resource context = statement.getContext();
				long contextId = context == null ? 0 : valueStore.storeValue(context);
				long[] quad = new long[] { subjId, predId, objId, contextId };
				writeQuad(out, quad);
				stats.update(quad);
			} catch (IOException e) {
				throw new RDFHandlerException(e);
			}
		}
	}

	private static final class BulkStats {

		private long maxSubject;
		private long maxPredicate;
		private long maxObject;
		private long maxContext;

		void update(long[] quad) {
			maxSubject = Math.max(maxSubject, quad[TripleStore.SUBJ_IDX]);
			maxPredicate = Math.max(maxPredicate, quad[TripleStore.PRED_IDX]);
			maxObject = Math.max(maxObject, quad[TripleStore.OBJ_IDX]);
			maxContext = Math.max(maxContext, quad[TripleStore.CONTEXT_IDX]);
		}

		long maxForField(char field) {
			switch (field) {
			case 's':
				return maxSubject;
			case 'p':
				return maxPredicate;
			case 'o':
				return maxObject;
			case 'c':
				return maxContext;
			default:
				throw new IllegalArgumentException("Unknown field: " + field);
			}
		}
	}
}
