/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.util.List;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Supplier;

class LmdbStatementIteratorCache {

	private final int cacheFrequencyThreshold;
	private final ConcurrentHashMap<IteratorKey, Integer> iteratorFrequencyMap = new ConcurrentHashMap<>();
	private final ConcurrentHashMap<IteratorKey, List<Long>> iteratorCache = new ConcurrentHashMap<>();

	LmdbStatementIteratorCache(int cacheFrequencyThreshold) {
		this.cacheFrequencyThreshold = cacheFrequencyThreshold;
	}

	void invalidateCache() {
		iteratorFrequencyMap.clear();
		iteratorCache.clear();
	}

	void incrementIteratorFrequencyMap(IteratorKey iterator) {
		iteratorFrequencyMap.compute(iterator, (key, value) -> value == null ? 0 : value + 1);
	}

	boolean shouldBeCached(IteratorKey iterator) {
		Integer frequency = iteratorFrequencyMap.get(iterator);
		return frequency != null && frequency > cacheFrequencyThreshold;
	}

	List<Long> getCachedIterator(IteratorKey iterator, Supplier<List<Long>> loader) {
		return iteratorCache.computeIfAbsent(iterator, key -> loader.get());
	}

	static final class IteratorKey {
		private final long subjId;
		private final long predId;
		private final long objId;
		private final boolean explicit;
		private final List<Long> contextIds;

		IteratorKey(long subjId, long predId, long objId, boolean explicit, List<Long> contextIds) {
			this.subjId = subjId;
			this.predId = predId;
			this.objId = objId;
			this.explicit = explicit;
			this.contextIds = List.copyOf(contextIds);
		}

		@Override
		public boolean equals(Object o) {
			if (this == o) {
				return true;
			}
			if (!(o instanceof IteratorKey)) {
				return false;
			}
			IteratorKey that = (IteratorKey) o;
			return subjId == that.subjId && predId == that.predId && objId == that.objId && explicit == that.explicit
					&& contextIds.equals(that.contextIds);
		}

		@Override
		public int hashCode() {
			return Objects.hash(subjId, predId, objId, explicit, contextIds);
		}
	}
}
