/*******************************************************************************
 * Copyright (c) 2025 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.EOFException;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.FileVisitResult;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.SimpleFileVisitor;
import java.nio.file.StandardOpenOption;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;

import org.eclipse.rdf4j.rio.RDFFormat;
import org.eclipse.rdf4j.rio.RDFHandlerException;
import org.eclipse.rdf4j.rio.RDFParseException;
import org.eclipse.rdf4j.rio.RDFParser;
import org.eclipse.rdf4j.rio.Rio;
import org.eclipse.rdf4j.rio.helpers.AbstractRDFHandler;
import org.eclipse.rdf4j.sail.SailException;
import org.eclipse.rdf4j.sail.lmdb.TripleStore.TripleIndex;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

class LmdbBulkLoader {

	private static final Logger logger = LoggerFactory.getLogger(LmdbBulkLoader.class);

	private static final String WORK_DIR = "bulk-load";
	private static final String IDS_FILE = "bulk-ids.bin";
	private static final int BUCKET_COUNT = 256;
	private static final int QUAD_LENGTH = 4;

	private final File dataDir;
	private final LmdbStoreConfig config;

	LmdbBulkLoader(File dataDir, LmdbStoreConfig config) {
		this.dataDir = dataDir;
		this.config = config;
	}

	void load(Path inputFile, RDFFormat format, String baseUri) throws IOException, SailException {
		if (!Files.exists(inputFile)) {
			throw new IOException("Input file not found: " + inputFile);
		}

		Path workDir = dataDir.toPath().resolve(WORK_DIR);
		boolean success = false;

		prepareDirectory(workDir);

		Path idFile = workDir.resolve(IDS_FILE);
		long[] maxIds = new long[QUAD_LENGTH];

		ValueStore valueStore = new ValueStore(new File(dataDir, "values"), config);
		try {
			try (TripleStore tripleStore = new TripleStore(new File(dataDir, "triples"), config, valueStore)) {
				if (tripleStore.hasTriples(true) || tripleStore.hasTriples(false)) {
					throw new SailException("Bulk load requires an empty LMDB store");
				}
				writeIdFile(valueStore, inputFile, idFile, format, baseUri, maxIds);
				loadIndexes(tripleStore, idFile, workDir, maxIds);
			}
			success = true;
		} finally {
			try {
				valueStore.close();
			} finally {
				if (success) {
					deleteDirectory(workDir);
				} else {
					logger.warn("Bulk load failed; preserving working directory at {}", workDir);
				}
			}
		}
	}

	private void writeIdFile(ValueStore valueStore, Path inputFile, Path idFile, RDFFormat format, String baseUri,
			long[] maxIds) throws IOException, SailException {
		valueStore.startTransaction(true);
		try (OutputStream output = Files.newOutputStream(idFile, StandardOpenOption.CREATE,
				StandardOpenOption.TRUNCATE_EXISTING);
				DataOutputStream dataOutput = new DataOutputStream(new BufferedOutputStream(output))) {
			RDFParser parser = Rio.createParser(format);
			parser.setRDFHandler(new AbstractRDFHandler() {
				@Override
				public void handleStatement(org.eclipse.rdf4j.model.Statement statement) throws RDFHandlerException {
					try {
						long subj = valueStore.storeValue(statement.getSubject());
						long pred = valueStore.storeValue(statement.getPredicate());
						long obj = valueStore.storeValue(statement.getObject());
						long ctx = statement.getContext() == null ? 0 : valueStore.storeValue(statement.getContext());

						dataOutput.writeLong(subj);
						dataOutput.writeLong(pred);
						dataOutput.writeLong(obj);
						dataOutput.writeLong(ctx);

						maxIds[TripleStore.SUBJ_IDX] = Math.max(maxIds[TripleStore.SUBJ_IDX], subj);
						maxIds[TripleStore.PRED_IDX] = Math.max(maxIds[TripleStore.PRED_IDX], pred);
						maxIds[TripleStore.OBJ_IDX] = Math.max(maxIds[TripleStore.OBJ_IDX], obj);
						maxIds[TripleStore.CONTEXT_IDX] = Math.max(maxIds[TripleStore.CONTEXT_IDX], ctx);
					} catch (IOException e) {
						throw new RDFHandlerException(e);
					}
				}
			});

			try (InputStream inputStream = Files.newInputStream(inputFile)) {
				parser.parse(inputStream, baseUri == null ? "" : baseUri);
			}
			valueStore.commit();
		} catch (RDFParseException | RDFHandlerException e) {
			valueStore.rollback();
			throw new SailException("Failed to parse input file for bulk load", e);
		} catch (IOException e) {
			valueStore.rollback();
			throw e;
		}
	}

	private void loadIndexes(TripleStore tripleStore, Path idFile, Path workDir, long[] maxIds) throws IOException {
		List<TripleIndex> indexes = tripleStore.getIndexes();
		boolean updateContexts = true;
		for (TripleIndex index : indexes) {
			Path indexDir = workDir.resolve("index-" + new String(index.getFieldSeq()));
			prepareDirectory(indexDir);
			int[] order = orderFor(index.getFieldSeq());
			List<Path> buckets = bucketQuads(idFile, indexDir, order[0], maxIds[order[0]]);

			tripleStore.startTransaction();
			try {
				for (Path bucket : buckets) {
					loadBucket(tripleStore, index, bucket, order, updateContexts);
				}
				tripleStore.commit();
			} catch (IOException e) {
				tripleStore.rollback();
				throw e;
			} finally {
				cleanupDirectory(indexDir);
			}
			updateContexts = false;
		}
	}

	private List<Path> bucketQuads(Path idFile, Path indexDir, int bucketField, long maxValue) throws IOException {
		Path[] bucketFiles = new Path[BUCKET_COUNT];
		DataOutputStream[] outputs = new DataOutputStream[BUCKET_COUNT];
		try {
			for (int i = 0; i < BUCKET_COUNT; i++) {
				Path bucketFile = indexDir.resolve(String.format("bucket-%03d.bin", i));
				bucketFiles[i] = bucketFile;
				outputs[i] = new DataOutputStream(new BufferedOutputStream(
						Files.newOutputStream(bucketFile, StandardOpenOption.CREATE,
								StandardOpenOption.TRUNCATE_EXISTING)));
			}

			try (DataInputStream input = new DataInputStream(new BufferedInputStream(Files.newInputStream(idFile)))) {
				while (true) {
					long s;
					try {
						s = input.readLong();
					} catch (EOFException eof) {
						break;
					}
					long p = input.readLong();
					long o = input.readLong();
					long c = input.readLong();
					long[] quad = new long[] { s, p, o, c };
					int bucket = bucketFor(quad[bucketField], maxValue);
					DataOutputStream out = outputs[bucket];
					out.writeLong(s);
					out.writeLong(p);
					out.writeLong(o);
					out.writeLong(c);
				}
			}
		} finally {
			for (DataOutputStream out : outputs) {
				if (out != null) {
					out.close();
				}
			}
		}
		return Arrays.asList(bucketFiles);
	}

	private void loadBucket(TripleStore tripleStore, TripleIndex index, Path bucketFile, int[] order,
			boolean updateContexts) throws IOException {
		long size = Files.size(bucketFile);
		if (size == 0) {
			return;
		}
		long recordSize = (long) Long.BYTES * QUAD_LENGTH;
		long recordCount = size / recordSize;
		if (size % recordSize != 0) {
			throw new IOException("Corrupted bucket file: " + bucketFile);
		}
		if (recordCount > Integer.MAX_VALUE) {
			throw new IOException("Bucket file too large to load in-memory: " + bucketFile);
		}

		long[][] quads = new long[(int) recordCount][QUAD_LENGTH];
		try (DataInputStream input = new DataInputStream(new BufferedInputStream(Files.newInputStream(bucketFile)))) {
			for (int i = 0; i < recordCount; i++) {
				long s = input.readLong();
				long p = input.readLong();
				long o = input.readLong();
				long c = input.readLong();
				quads[i][0] = s;
				quads[i][1] = p;
				quads[i][2] = o;
				quads[i][3] = c;
			}
		}

		Arrays.sort(quads, quadComparator(order));

		try (TripleStore.IndexWriter writer = tripleStore.createIndexWriter(index, true, updateContexts, true)) {
			for (long[] quad : quads) {
				writer.store(quad);
			}
		}

		Files.deleteIfExists(bucketFile);
	}

	private int bucketFor(long value, long maxValue) {
		if (maxValue <= 0) {
			return 0;
		}
		double ratio = (double) value / (double) (maxValue + 1L);
		int bucket = (int) (ratio * BUCKET_COUNT);
		return Math.min(bucket, BUCKET_COUNT - 1);
	}

	private Comparator<long[]> quadComparator(int[] order) {
		return (left, right) -> {
			for (int index : order) {
				int diff = Long.compare(left[index], right[index]);
				if (diff != 0) {
					return diff;
				}
			}
			return 0;
		};
	}

	private int[] orderFor(char[] fieldSeq) {
		int[] order = new int[fieldSeq.length];
		for (int i = 0; i < fieldSeq.length; i++) {
			order[i] = fieldIndex(fieldSeq[i]);
		}
		return order;
	}

	private int fieldIndex(char field) {
		switch (field) {
		case 's':
			return TripleStore.SUBJ_IDX;
		case 'p':
			return TripleStore.PRED_IDX;
		case 'o':
			return TripleStore.OBJ_IDX;
		case 'c':
			return TripleStore.CONTEXT_IDX;
		default:
			throw new IllegalArgumentException("Unknown field: " + field);
		}
	}

	private void prepareDirectory(Path dir) throws IOException {
		cleanupDirectory(dir);
		Files.createDirectories(dir);
	}

	private void cleanupDirectory(Path dir) throws IOException {
		if (!Files.exists(dir)) {
			return;
		}
		Files.walkFileTree(dir, new SimpleFileVisitor<>() {
			@Override
			public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
				Files.deleteIfExists(file);
				return FileVisitResult.CONTINUE;
			}

			@Override
			public FileVisitResult postVisitDirectory(Path directory, IOException exc) throws IOException {
				if (!directory.equals(dir)) {
					Files.deleteIfExists(directory);
				}
				return FileVisitResult.CONTINUE;
			}
		});
	}

	private void deleteDirectory(Path dir) {
		try {
			cleanupDirectory(dir);
			Files.deleteIfExists(dir);
		} catch (IOException e) {
			logger.warn("Failed to delete bulk load working directory {}", dir, e);
		}
	}

}
