/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.workbench.sailstack;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.Test;

class SailStackValidatorTest {
	private final SailStackValidator validator = new SailStackValidator();

	@Test
	void rejectsMissingBaseStore() {
		SailStackSpec spec = new SailStackSpec();
		RepoSpec repo = new RepoSpec();
		repo.setId("missing-base");
		spec.setRepo(repo);

		SailLayerSpec lucene = new SailLayerSpec();
		lucene.setType(SailLayerType.LUCENE);
		lucene.setConfig(Map.of("indexDir", "lucene"));
		spec.setStack(List.of(lucene));

		SailStackValidationResult result = validator.validate(spec);
		assertThat(result.getErrors()).anyMatch(error -> error.contains("base store"));
	}

	@Test
	void requiresLuceneIndexDir() {
		SailStackSpec spec = new SailStackSpec();
		RepoSpec repo = new RepoSpec();
		repo.setId("lucene-missing");
		spec.setRepo(repo);

		SailLayerSpec lucene = new SailLayerSpec();
		lucene.setType(SailLayerType.LUCENE);
		SailLayerSpec base = new SailLayerSpec();
		base.setType(SailLayerType.MEMORY);
		base.setConfig(Map.of("persist", true));
		spec.setStack(List.of(lucene, base));

		SailStackValidationResult result = validator.validate(spec);
		assertThat(result.getErrors()).anyMatch(error -> error.contains("Lucene"));
	}
}
