/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.workbench.sailstack;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;
import java.util.Map;

import org.eclipse.rdf4j.repository.config.RepositoryConfig;
import org.eclipse.rdf4j.repository.sail.config.SailRepositoryConfig;
import org.eclipse.rdf4j.sail.config.SailImplConfig;
import org.eclipse.rdf4j.sail.inferencer.fc.config.SchemaCachingRDFSInferencerConfig;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.eclipse.rdf4j.sail.lucene.impl.config.LuceneSailConfig;
import org.eclipse.rdf4j.sail.memory.config.MemoryStoreConfig;
import org.junit.jupiter.api.Test;

class SailStackConfigGeneratorTest {
	private final SailStackConfigGenerator generator = new SailStackConfigGenerator();

	@Test
	void generatesMemoryStoreConfig() {
		SailStackSpec spec = new SailStackSpec();
		RepoSpec repo = new RepoSpec();
		repo.setId("memory-repo");
		repo.setTitle("Memory Repository");
		spec.setRepo(repo);

		SailLayerSpec base = new SailLayerSpec();
		base.setType(SailLayerType.MEMORY);
		base.setConfig(Map.of("persist", true, "syncDelay", 0));
		spec.setStack(List.of(base));

		SailStackConfigResult result = generator.generate(spec);
		assertThat(result.getValidation().getErrors()).isEmpty();
		RepositoryConfig config = result.getRepositoryConfig();
		assertThat(config.getID()).isEqualTo("memory-repo");
		assertThat(config.getTitle()).isEqualTo("Memory Repository");

		SailRepositoryConfig repoConfig = (SailRepositoryConfig) config.getRepositoryImplConfig();
		assertThat(repoConfig.getSailImplConfig()).isInstanceOf(MemoryStoreConfig.class);
	}

	@Test
	void wrapsLuceneAboveRdfsAboveLmdb() {
		SailStackSpec spec = new SailStackSpec();
		RepoSpec repo = new RepoSpec();
		repo.setId("stacked");
		spec.setRepo(repo);

		SailLayerSpec lucene = new SailLayerSpec();
		lucene.setType(SailLayerType.LUCENE);
		lucene.setConfig(Map.of("indexDir", "indexes/lucene"));
		SailLayerSpec rdfs = new SailLayerSpec();
		rdfs.setType(SailLayerType.RDFS);
		SailLayerSpec base = new SailLayerSpec();
		base.setType(SailLayerType.LMDB);
		base.setConfig(Map.of("tripleIndexes", "spoc,posc"));
		spec.setStack(List.of(lucene, rdfs, base));

		SailStackConfigResult result = generator.generate(spec);
		assertThat(result.getValidation().getErrors()).isEmpty();
		assertThat(result.getValidation().getWarnings()).isNotEmpty();

		RepositoryConfig config = result.getRepositoryConfig();
		SailRepositoryConfig repoConfig = (SailRepositoryConfig) config.getRepositoryImplConfig();
		SailImplConfig top = repoConfig.getSailImplConfig();
		assertThat(top).isInstanceOf(LuceneSailConfig.class);
		SailImplConfig rdfsConfig = ((LuceneSailConfig) top).getDelegate();
		assertThat(rdfsConfig).isInstanceOf(SchemaCachingRDFSInferencerConfig.class);
		SailImplConfig baseConfig = ((SchemaCachingRDFSInferencerConfig) rdfsConfig).getDelegate();
		assertThat(baseConfig).isInstanceOf(LmdbStoreConfig.class);
	}
}
