/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.Comparator;

import org.eclipse.rdf4j.common.iteration.CloseableIteration;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.Statement;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.algebra.evaluation.TripleSource;
import org.eclipse.rdf4j.query.impl.EmptyBindingSet;
import org.eclipse.rdf4j.sail.lmdb.model.LmdbValue;
import org.junit.jupiter.api.Test;

class LmdbOverlayEvaluationDatasetFastPathTest {

	@Test
	void arrayPathUsesCurrentDatasetWhenOverlayIsNotThreadLocal() {
		TrackingDataset currentDataset = new TrackingDataset();
		LmdbOverlayEvaluationDataset overlay = new LmdbOverlayEvaluationDataset(new FailingTripleSource(), null);

		LmdbEvaluationStrategy.setCurrentDataset(currentDataset);
		try {
			RecordIterator iterator = overlay.getRecordIterator(new long[] { LmdbValue.UNKNOWN_ID }, -1, -1, 0, -1,
					new long[] {
							LmdbValue.UNKNOWN_ID, LmdbValue.UNKNOWN_ID, LmdbValue.UNKNOWN_ID, LmdbValue.UNKNOWN_ID
					});

			assertThat(iterator).isSameAs(currentDataset.arrayIterator);
			assertThat(currentDataset.arrayApiUsed).isTrue();
			assertThat(currentDataset.patternApiUsed).isFalse();
		} finally {
			LmdbEvaluationStrategy.clearCurrentDataset();
		}
	}

	@Test
	void statementPatternPathUsesCurrentDatasetWhenOverlayIsNotThreadLocal() {
		TrackingDataset currentDataset = new TrackingDataset();
		LmdbOverlayEvaluationDataset overlay = new LmdbOverlayEvaluationDataset(new FailingTripleSource(), null);
		StatementPattern pattern = new StatementPattern(new Var("s"), new Var("p"), new Var("o"));

		LmdbEvaluationStrategy.setCurrentDataset(currentDataset);
		try {
			RecordIterator iterator = overlay.getRecordIterator(pattern, EmptyBindingSet.getInstance());

			assertThat(iterator).isSameAs(currentDataset.patternIterator);
			assertThat(currentDataset.patternApiUsed).isTrue();
			assertThat(currentDataset.arrayApiUsed).isFalse();
		} finally {
			LmdbEvaluationStrategy.clearCurrentDataset();
		}
	}

	private static final class TrackingDataset implements LmdbEvaluationDataset {
		private final RecordIterator arrayIterator = emptyIterator();
		private final RecordIterator patternIterator = emptyIterator();
		private boolean arrayApiUsed;
		private boolean patternApiUsed;

		@Override
		public RecordIterator getRecordIterator(StatementPattern pattern, BindingSet bindings) {
			patternApiUsed = true;
			return patternIterator;
		}

		@Override
		public RecordIterator getRecordIterator(long[] binding, int subjIndex, int predIndex, int objIndex,
				int ctxIndex,
				long[] patternIds) {
			arrayApiUsed = true;
			return arrayIterator;
		}

		@Override
		public ValueStore getValueStore() {
			return null;
		}
	}

	private static final class FailingTripleSource implements TripleSource {
		@Override
		public CloseableIteration<? extends Statement> getStatements(Resource subj, IRI pred, Value obj,
				Resource... contexts) {
			throw new AssertionError("overlay materialization path should not be used");
		}

		@Override
		public Comparator<Value> getComparator() {
			return null;
		}

		@Override
		public org.eclipse.rdf4j.model.ValueFactory getValueFactory() {
			return SimpleValueFactory.getInstance();
		}
	}

	private static RecordIterator emptyIterator() {
		return new RecordIterator() {
			@Override
			public long[] next() {
				return null;
			}

			@Override
			public void close() {
			}
		};
	}
}
