/*******************************************************************************
 * Copyright (c) 2025 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import org.eclipse.rdf4j.common.iteration.CloseableIteration;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.Statement;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.rio.RDFFormat;
import org.eclipse.rdf4j.sail.SailConnection;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class LmdbBulkLoadTest {

	@TempDir
	Path dataDir;

	@Test
	void bulkLoadPopulatesIndexesAndContexts() throws Exception {
		Path dataFile = dataDir.resolve("bulk-load.nq");
		String data = String.join("\n",
				"<urn:s1> <urn:p1> <urn:o1> <urn:ctx1> .",
				"<urn:s1> <urn:p2> \"literal\" <urn:ctx1> .",
				"<urn:s2> <urn:p1> <urn:o1> .",
				"");
		Files.writeString(dataFile, data, StandardCharsets.UTF_8);

		LmdbStore store = new LmdbStore(dataDir.toFile(), new LmdbStoreConfig("spoc,posc,cspo"));
		store.init();
		try {
			store.bulkLoad(dataFile, RDFFormat.NQUADS);

			ValueFactory vf = store.getValueFactory();
			Resource s1 = vf.createIRI("urn:s1");
			IRI p1 = vf.createIRI("urn:p1");
			Resource ctx1 = vf.createIRI("urn:ctx1");

			try (SailConnection conn = store.getConnection()) {
				assertEquals(3, conn.size());
				assertEquals(2, countStatements(conn.getStatements(s1, null, null, false)));
				assertEquals(2, countStatements(conn.getStatements(null, p1, null, false)));
				assertEquals(2, countStatements(conn.getStatements(null, null, null, false, ctx1)));
			}
		} finally {
			store.shutDown();
		}
	}

	private long countStatements(CloseableIteration<? extends Statement> iteration) throws Exception {
		try (CloseableIteration<? extends Statement> it = iteration) {
			long count = 0;
			while (it.hasNext()) {
				it.next();
				count++;
			}
			return count;
		}
	}
}
