/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotSame;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

import org.junit.jupiter.api.Test;

class LmdbStatementIteratorCacheTest {

	@Test
	void cachesPopularIteratorsAfterThreshold() {
		LmdbStatementIteratorCache cache = new LmdbStatementIteratorCache(2);
		LmdbStatementIteratorCache.IteratorKey key = new LmdbStatementIteratorCache.IteratorKey(1L, 2L, 3L, true,
				List.of(0L));

		AtomicInteger supplierCalls = new AtomicInteger();
		assertFalse(cache.shouldBeCached(key));
		cache.incrementIteratorFrequencyMap(key);
		cache.incrementIteratorFrequencyMap(key);
		cache.incrementIteratorFrequencyMap(key);
		cache.incrementIteratorFrequencyMap(key);
		assertTrue(cache.shouldBeCached(key));

		List<Long> first = cache.getCachedIterator(key, () -> {
			supplierCalls.incrementAndGet();
			return List.of(1L, 2L, 3L);
		});
		List<Long> second = cache.getCachedIterator(key, () -> {
			supplierCalls.incrementAndGet();
			return List.of(4L);
		});

		assertSame(first, second);
		assertEquals(1, supplierCalls.get());

		cache.invalidateCache();
		List<Long> third = cache.getCachedIterator(key, () -> {
			supplierCalls.incrementAndGet();
			return List.of(5L);
		});
		assertNotSame(second, third);
		assertEquals(2, supplierCalls.get());
	}
}
