/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.assertj.core.api.Assertions.assertThat;

import java.lang.reflect.Field;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.IdentityHashMap;
import java.util.List;
import java.util.Set;

import org.eclipse.rdf4j.common.transaction.IsolationLevels;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.QueryEvaluationException;
import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.sail.base.SailDataset;
import org.eclipse.rdf4j.sail.base.SailSource;
import org.eclipse.rdf4j.sail.lmdb.model.LmdbValue;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class LmdbSailDatasetPreviousRightReuseTest {

	private static final String NS = "http://example.com/";

	@Test
	void standardIteratorTransferUnwrapsWrappedPreviousRight(@TempDir Path tempDir) throws Exception {
		try (StoreContext context = createStore(tempDir)) {
			ValueFactory vf = SimpleValueFactory.getInstance();
			IRI alice = vf.createIRI(NS, "alice");
			IRI bob = vf.createIRI(NS, "bob");
			IRI carol = vf.createIRI(NS, "carol");
			IRI knows = vf.createIRI(NS, "knows");

			context.add(alice, knows, bob);
			context.add(bob, knows, carol);

			long knowsId = context.valueStore().getId(knows);
			long aliceId = context.valueStore().getId(alice);
			long bobId = context.valueStore().getId(bob);
			long carolId = context.valueStore().getId(carol);
			long[] patternIds = {
					LmdbValue.UNKNOWN_ID, knowsId, LmdbValue.UNKNOWN_ID, LmdbValue.UNKNOWN_ID
			};

			RecordIterator first = context.dataset()
					.getRecordIterator(new long[] { aliceId, bobId }, 0, -1, 1, -1,
							patternIds, new long[2], new long[4], null);
			RecordIterator second = null;
			try {
				RecordIterator firstBase = unwrapBase(first);
				assertThat(firstBase).isInstanceOf(LmdbRecordIterator.class);
				assertThat(collect(first)).containsExactly(new long[] { aliceId, bobId });

				second = context.dataset()
						.getRecordIterator(new long[] { bobId, carolId }, 0, -1, 1, -1, patternIds,
								new long[2], new long[4], first);
				RecordIterator secondBase = unwrapBase(second);
				assertThat(secondBase).isInstanceOf(LmdbRecordIterator.class);
				assertThat(cursorOf(secondBase)).isEqualTo(cursorOf(firstBase));
				assertThat(collect(second)).containsExactly(new long[] { bobId, carolId });
			} finally {
				if (second != null) {
					second.close();
				}
				first.close();
			}
		}
	}

	@Test
	void dupIteratorTransferUnwrapsWrappedPreviousRight(@TempDir Path tempDir) throws Exception {
		try (StoreContext context = createStore(tempDir)) {
			ValueFactory vf = SimpleValueFactory.getInstance();
			IRI alice = vf.createIRI(NS, "alice");
			IRI bob = vf.createIRI(NS, "bob");
			IRI carol = vf.createIRI(NS, "carol");
			IRI knows = vf.createIRI(NS, "knows");

			context.add(alice, knows, bob);
			context.add(bob, knows, carol);

			long knowsId = context.valueStore().getId(knows);
			long aliceId = context.valueStore().getId(alice);
			long bobId = context.valueStore().getId(bob);
			long carolId = context.valueStore().getId(carol);
			long[] patternIds = {
					LmdbValue.UNKNOWN_ID, knowsId, LmdbValue.UNKNOWN_ID, LmdbValue.UNKNOWN_ID
			};

			RecordIterator first = context.dataset()
					.getRecordIterator(new long[] { aliceId, LmdbValue.UNKNOWN_ID }, 0,
							-1, 1, -1, patternIds, new long[2], new long[4], null);
			RecordIterator second = null;
			try {
				RecordIterator firstBase = unwrapBase(first);
				assertThat(firstBase).isInstanceOf(LmdbDupRecordIterator.class);
				assertThat(collect(first)).containsExactly(new long[] { aliceId, bobId });

				second = context.dataset()
						.getRecordIterator(new long[] { bobId, LmdbValue.UNKNOWN_ID }, 0, -1, 1, -1,
								patternIds, new long[2], new long[4], first);
				RecordIterator secondBase = unwrapBase(second);
				assertThat(secondBase).isInstanceOf(LmdbDupRecordIterator.class);
				assertThat(cursorOf(secondBase)).isEqualTo(cursorOf(firstBase));
				assertThat(collect(second)).containsExactly(new long[] { bobId, carolId });
			} finally {
				if (second != null) {
					second.close();
				}
				first.close();
			}
		}
	}

	private static StoreContext createStore(Path tempDir) throws Exception {
		LmdbStore store = new LmdbStore(tempDir.toFile());
		SailRepository repository = new SailRepository(store);
		repository.init();

		SailSource branch = store.getBackingStore().getExplicitSailSource();
		SailDataset sailDataset = branch.dataset(IsolationLevels.SNAPSHOT_READ);
		return new StoreContext(repository, branch, sailDataset);
	}

	private static List<long[]> collect(RecordIterator iterator) throws QueryEvaluationException {
		List<long[]> values = new ArrayList<>();
		long[] next;
		while ((next = iterator.next()) != null) {
			values.add(next.clone());
		}
		return values;
	}

	private static RecordIterator unwrapBase(RecordIterator iterator) throws Exception {
		RecordIterator current = iterator;
		Set<RecordIterator> seen = java.util.Collections.newSetFromMap(new IdentityHashMap<>());
		while (current != null && seen.add(current)) {
			if (current instanceof LmdbRecordIterator || current instanceof LmdbDupRecordIterator) {
				return current;
			}
			current = findNestedIterator(current);
		}
		throw new AssertionError("did not find LMDB iterator delegate");
	}

	private static RecordIterator findNestedIterator(RecordIterator iterator) throws Exception {
		for (Field field : iterator.getClass().getDeclaredFields()) {
			if (!RecordIterator.class.isAssignableFrom(field.getType())) {
				continue;
			}
			field.setAccessible(true);
			Object value = field.get(iterator);
			if (value instanceof RecordIterator && value != iterator) {
				return (RecordIterator) value;
			}
		}
		return null;
	}

	private static long cursorOf(RecordIterator iterator) throws Exception {
		Field field = iterator.getClass().getDeclaredField("cursor");
		field.setAccessible(true);
		return field.getLong(iterator);
	}

	private static final class StoreContext implements AutoCloseable {
		private final SailRepository repository;
		private final SailSource branch;
		private final SailDataset sailDataset;

		private StoreContext(SailRepository repository, SailSource branch, SailDataset sailDataset) {
			this.repository = repository;
			this.branch = branch;
			this.sailDataset = sailDataset;
		}

		private void add(IRI subj, IRI pred, IRI obj) {
			try (RepositoryConnection connection = repository.getConnection()) {
				connection.add(subj, pred, obj);
			}
		}

		private LmdbEvaluationDataset dataset() {
			return (LmdbEvaluationDataset) sailDataset;
		}

		private ValueStore valueStore() {
			return dataset().getValueStore();
		}

		@Override
		public void close() throws Exception {
			sailDataset.close();
			branch.close();
			repository.shutDown();
		}
	}
}
