/*******************************************************************************
 * Copyright (c) 2025 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;

import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.rio.RDFFormat;
import org.eclipse.rdf4j.sail.SailException;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.eclipse.rdf4j.sail.lmdb.model.LmdbValue;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class LmdbBulkLoadTest {

	@TempDir
	Path dataDir;

	@Test
	void testBulkLoadNQuads() throws Exception {
		Path inputFile = copyResourceToTempFile("bulkload/bulk-load.nq");
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,posc,cspo");
		LmdbStore store = new LmdbStore(dataDir.toFile(), config);

		store.bulkLoad(inputFile, RDFFormat.NQUADS, null);

		SailRepository repository = new SailRepository(store);
		repository.init();
		try (RepositoryConnection connection = repository.getConnection()) {
			assertEquals(3L, connection.size());
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void testBulkLoadRejectsNonEmptyStore() throws Exception {
		Path inputFile = copyResourceToTempFile("bulkload/bulk-load.nq");
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,posc,cspo");
		ValueFactory valueFactory = SimpleValueFactory.getInstance();

		LmdbStore seedStore = new LmdbStore(dataDir.toFile(), config);
		SailRepository repository = new SailRepository(seedStore);
		repository.init();
		try (RepositoryConnection connection = repository.getConnection()) {
			connection.add(valueFactory.createIRI("urn:seed-subject"), valueFactory.createIRI("urn:seed-predicate"),
					valueFactory.createIRI("urn:seed-object"));
		} finally {
			repository.shutDown();
		}

		LmdbStore store = new LmdbStore(dataDir.toFile(), config);

		assertThrows(SailException.class, () -> store.bulkLoad(inputFile, RDFFormat.NQUADS, null));

		ValueStore valueStore = new ValueStore(dataDir.resolve("values").toFile(), config);
		try {
			long id = valueStore.getId(valueFactory.createIRI("urn:subject-1"));
			assertEquals(LmdbValue.UNKNOWN_ID, id);
		} finally {
			valueStore.close();
		}
	}

	private Path copyResourceToTempFile(String resource) throws IOException {
		Path tempFile = Files.createTempFile("lmdb-bulk-load", ".nq");
		try (InputStream input = LmdbBulkLoadTest.class.getClassLoader().getResourceAsStream(resource)) {
			if (input == null) {
				throw new IOException("Resource not found: " + resource);
			}
			Files.copy(input, tempFile, StandardCopyOption.REPLACE_EXISTING);
		}
		return tempFile;
	}
}
