/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lucene;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.Set;

import org.eclipse.rdf4j.common.iteration.CloseableIteration;
import org.eclipse.rdf4j.common.iteration.CloseableIteratorIteration;
import org.eclipse.rdf4j.common.order.StatementOrder;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Literal;
import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.Statement;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.model.util.LexicalValueComparator;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.sail.NotifyingSail;
import org.eclipse.rdf4j.sail.NotifyingSailConnection;
import org.eclipse.rdf4j.sail.SailException;
import org.eclipse.rdf4j.sail.helpers.NotifyingSailConnectionWrapper;
import org.eclipse.rdf4j.sail.helpers.NotifyingSailWrapper;
import org.eclipse.rdf4j.sail.memory.MemoryStore;
import org.junit.jupiter.api.Test;

class ReindexBatchingTest {
	private static final SimpleValueFactory VALUE_FACTORY = SimpleValueFactory.getInstance();

	@Test
	void reindexSortsBatchesBeforeIndexing() throws Exception {
		RecordingSearchIndex index = new RecordingSearchIndex();
		MemoryStore memoryStore = new MemoryStore();
		NotifyingSail unsortedSail = new UnsortedStatementsSail(memoryStore);

		TestLuceneSail sail = new TestLuceneSail(3, index);
		sail.setBaseSail(unsortedSail);
		sail.setReindexQuery("SELECT ?s ?p ?o ?c WHERE {{?s ?p ?o} UNION {GRAPH ?c {?s ?p ?o.}}}");
		sail.init();

		List<Statement> statements = List.of(
				VALUE_FACTORY.createStatement(VALUE_FACTORY.createIRI("urn:subject3"),
						VALUE_FACTORY.createIRI("urn:predicate"), VALUE_FACTORY.createLiteral("z")),
				VALUE_FACTORY.createStatement(VALUE_FACTORY.createIRI("urn:subject1"),
						VALUE_FACTORY.createIRI("urn:predicate"), VALUE_FACTORY.createLiteral("b")),
				VALUE_FACTORY.createStatement(VALUE_FACTORY.createIRI("urn:subject2"),
						VALUE_FACTORY.createIRI("urn:predicate"), VALUE_FACTORY.createLiteral("a")),
				VALUE_FACTORY.createStatement(VALUE_FACTORY.createIRI("urn:subject1"),
						VALUE_FACTORY.createIRI("urn:predicate"), VALUE_FACTORY.createLiteral("a")),
				VALUE_FACTORY.createStatement(VALUE_FACTORY.createIRI("urn:subject2"),
						VALUE_FACTORY.createIRI("urn:predicate"), VALUE_FACTORY.createLiteral("c"))
		);

		try (NotifyingSailConnection connection = unsortedSail.getConnection()) {
			connection.begin();
			for (Statement statement : statements) {
				connection.addStatement(statement.getSubject(), statement.getPredicate(), statement.getObject(),
						statement.getContext());
			}
			connection.commit();
		}

		sail.reindex();

		assertThat(index.getBatches()).hasSize(2);
		assertThat(index.getIndexedStatements()).containsExactlyInAnyOrderElementsOf(statements);
		sail.shutDown();
	}

	private static final class TestLuceneSail extends LuceneSail {
		private final int batchSize;
		private final SearchIndex index;

		private TestLuceneSail(int batchSize, SearchIndex index) {
			this.batchSize = batchSize;
			this.index = index;
			setLuceneIndex(index);
		}

		@Override
		protected int getReindexBatchSize() {
			return batchSize;
		}

		@Override
		protected void initializeLuceneIndex() throws Exception {
			setLuceneIndex(index);
		}
	}

	private static final class UnsortedStatementsSail extends NotifyingSailWrapper {
		private UnsortedStatementsSail(NotifyingSail baseSail) {
			super(baseSail);
		}

		@Override
		public NotifyingSailConnection getConnection() throws SailException {
			NotifyingSailConnection connection = super.getConnection();
			return new NotifyingSailConnectionWrapper(connection) {
				@Override
				public CloseableIteration<? extends Statement> getStatements(Resource subj, IRI pred, Value obj,
						boolean includeInferred, Resource... contexts) throws SailException {
					List<Statement> statements = new ArrayList<>();
					try (CloseableIteration<? extends Statement> iteration = super.getStatements(subj, pred, obj,
							includeInferred, contexts)) {
						while (iteration.hasNext()) {
							statements.add(iteration.next());
						}
					}
					Collections.reverse(statements);
					return new CloseableIteratorIteration<>(statements.iterator());
				}

				@Override
				public CloseableIteration<? extends Statement> getStatements(StatementOrder statementOrder,
						Resource subj,
						IRI pred, Value obj, boolean includeInferred, Resource... contexts) throws SailException {
					return getStatements(subj, pred, obj, includeInferred, contexts);
				}
			};
		}
	}

	private static final class RecordingSearchIndex implements SearchIndex {
		private final Comparator<Value> valueComparator = new LexicalValueComparator();
		private final Comparator<Statement> statementComparator = Comparator
				.comparing(Statement::getSubject, valueComparator)
				.thenComparing(Statement::getPredicate, valueComparator)
				.thenComparing(Statement::getObject, valueComparator)
				.thenComparing(Statement::getContext, Comparator.nullsFirst(valueComparator));
		private final List<List<Statement>> batches = new ArrayList<>();

		List<List<Statement>> getBatches() {
			return batches;
		}

		List<Statement> getIndexedStatements() {
			List<Statement> statements = new ArrayList<>();
			for (List<Statement> batch : batches) {
				statements.addAll(batch);
			}
			return statements;
		}

		@Override
		public void initialize(Properties parameters) {
			// no-op for test stub
		}

		@Override
		public Collection<BindingSet> evaluate(SearchQueryEvaluator query) {
			throw new UnsupportedOperationException("Query evaluation not used in reindex tests");
		}

		@Override
		public void shutDown() {
			// no-op for test stub
		}

		@Override
		public boolean accept(Literal literal) {
			return true;
		}

		@Override
		public boolean isGeoField(String propertyName) {
			return false;
		}

		@Override
		public boolean isTypeStatement(Statement statement) {
			return false;
		}

		@Override
		public boolean isTypeFilteringEnabled() {
			return false;
		}

		@Override
		public boolean isIndexedTypeStatement(Statement statement) {
			return false;
		}

		@Override
		public Map<IRI, Set<IRI>> getIndexedTypeMapping() {
			return Map.of();
		}

		@Override
		public void begin() {
			// no-op for test stub
		}

		@Override
		public void commit() {
			// no-op for test stub
		}

		@Override
		public void rollback() {
			// no-op for test stub
		}

		@Override
		public void addStatement(Statement statement) {
			throw new UnsupportedOperationException("Single-statement indexing not used in reindex tests");
		}

		@Override
		public void removeStatement(Statement statement) {
			throw new UnsupportedOperationException("Single-statement indexing not used in reindex tests");
		}

		@Override
		public void addRemoveStatements(Collection<Statement> added, Collection<Statement> removed) {
			assertThat(removed).isEmpty();
			List<Statement> batch = new ArrayList<>(added);
			List<Statement> sorted = new ArrayList<>(batch);
			sorted.sort(statementComparator);
			assertThat(batch).containsExactlyElementsOf(sorted);
			batches.add(batch);
		}

		@Override
		public void clearContexts(Resource... contexts) {
			// no-op for test stub
		}

		@Override
		public void addDocuments(Resource subject, List<Statement> statements) throws IOException {
			throw new AssertionError("addDocuments should not be used in batched reindexing");
		}

		@Override
		public void clear() {
			// no-op for test stub
		}
	}
}
