/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.query.algebra.helpers;

import java.nio.charset.StandardCharsets;

import org.eclipse.rdf4j.common.annotation.Experimental;
import org.eclipse.rdf4j.query.algebra.BinaryTupleOperator;
import org.eclipse.rdf4j.query.algebra.QueryModelNode;
import org.eclipse.rdf4j.query.algebra.QueryRoot;

/**
 * Assigns deterministic plan node ids and computes a plan shape hash for a query model tree.
 */
@Experimental
public final class PlanNodeDiagnostics {

	private PlanNodeDiagnostics() {
	}

	/**
	 * Assign plan node ids and plan shape hash to all nodes in the tree.
	 *
	 * @param root the root of the query model tree
	 * @return the computed plan shape hash, or {@code -1} if root is null
	 */
	public static long assignPlanMetadata(QueryModelNode root) {
		if (root == null) {
			return -1;
		}

		QueryModelNode planRoot = root;
		if (planRoot instanceof QueryRoot) {
			planRoot = ((QueryRoot) planRoot).getArg();
		}

		if (planRoot == null) {
			return -1;
		}

		PlanShapeHasher hasher = new PlanShapeHasher();
		planRoot.visit(hasher);
		long planShapeHash = hasher.getPlanShapeHash();

		PlanNodeAssigner assigner = new PlanNodeAssigner(planShapeHash);
		planRoot.visit(assigner);

		return planShapeHash;
	}

	private static final class PlanNodeAssigner extends AbstractQueryModelVisitor<RuntimeException> {

		private final long planShapeHash;
		private int nextId;

		private PlanNodeAssigner(long planShapeHash) {
			this.planShapeHash = planShapeHash;
		}

		@Override
		protected void meetNode(QueryModelNode node) {
			node.setPlanNodeId(nextId++);
			node.setPlanShapeHash(planShapeHash);
			super.meetNode(node);
		}
	}

	private static final class PlanShapeHasher extends AbstractQueryModelVisitor<RuntimeException> {

		private static final long FNV64_OFFSET_BASIS = 0xcbf29ce484222325L;
		private static final long FNV64_PRIME = 0x100000001b3L;

		private long hash = FNV64_OFFSET_BASIS;

		private long getPlanShapeHash() {
			return hash;
		}

		@Override
		protected void meetNode(QueryModelNode node) {
			updateHash(node.getSignature());

			if (node instanceof BinaryTupleOperator) {
				updateHash(((BinaryTupleOperator) node).getAlgorithmName());
			}

			super.meetNode(node);
		}

		private void updateHash(String value) {
			if (value == null) {
				updateHashBytes(new byte[] { 0 });
				return;
			}
			updateHashBytes(value.getBytes(StandardCharsets.UTF_8));
		}

		private void updateHashBytes(byte[] bytes) {
			for (byte b : bytes) {
				hash ^= (b & 0xff);
				hash *= FNV64_PRIME;
			}
		}
	}
}
