/*******************************************************************************
 * Copyright (c) 2025 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.nativerdf;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.nio.file.Path;
import java.util.List;
import java.util.stream.Collectors;

import org.eclipse.rdf4j.common.iteration.CloseableIteration;
import org.eclipse.rdf4j.common.order.StatementOrder;
import org.eclipse.rdf4j.common.transaction.IsolationLevels;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Statement;
import org.eclipse.rdf4j.model.util.Values;
import org.eclipse.rdf4j.model.vocabulary.RDFS;
import org.eclipse.rdf4j.sail.NotifyingSailConnection;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class NativeStoreOrderedStatementsTest {

	private static final String NAMESPACE = "http://example.com/";

	@Test
	void ordersStatementsBySubject(@TempDir Path dataDir) {
		NativeStore nativeStore = new NativeStore(dataDir.toFile(), "spoc");
		nativeStore.setWalEnabled(false);

		nativeStore.init();
		try (NotifyingSailConnection connection = nativeStore.getConnection()) {
			connection.begin();
			connection.addStatement(Values.iri(NAMESPACE, "d"), RDFS.LABEL, Values.literal("b"));
			connection.addStatement(Values.iri(NAMESPACE, "e"), RDFS.LABEL, Values.literal("a"));
			connection.addStatement(Values.iri(NAMESPACE, "a"), RDFS.LABEL, Values.literal("e"));
			connection.addStatement(Values.iri(NAMESPACE, "c"), RDFS.LABEL, Values.literal("c"));
			connection.addStatement(Values.iri(NAMESPACE, "b"), RDFS.LABEL, Values.literal("d"));
			connection.commit();

			connection.begin(IsolationLevels.NONE);
			try (CloseableIteration<? extends Statement> statements = connection.getStatements(StatementOrder.S, null,
					null, null, false)) {
				List<String> subjects = statements.stream()
						.map(Statement::getSubject)
						.map(IRI.class::cast)
						.map(IRI::getLocalName)
						.collect(Collectors.toList());

				assertEquals(List.of("a", "b", "c", "d", "e"), subjects);
			}

			connection.commit();
		} finally {
			nativeStore.shutDown();
		}
	}
}
