/*******************************************************************************
 * Copyright (c) 2025 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.nativerdf;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.File;
import java.lang.reflect.Field;

import org.eclipse.rdf4j.model.BNode;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.model.util.ModelBuilder;
import org.eclipse.rdf4j.model.vocabulary.CONFIG;
import org.eclipse.rdf4j.sail.base.SailStore;
import org.eclipse.rdf4j.sail.base.SnapshotSailStore;
import org.eclipse.rdf4j.sail.nativerdf.config.NativeStoreConfig;
import org.eclipse.rdf4j.sail.nativerdf.config.NativeStoreFactory;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class NativeStoreMemoryMappedTxnStatusFileConfigTest {

	private static final String MEMORY_MAPPED_ENABLED_PROP = "org.eclipse.rdf4j.sail.nativerdf.MemoryMappedTxnStatusFile.enabled";

	@TempDir
	File dataDir;

	@AfterEach
	void clearSystemProperty() {
		System.clearProperty(MEMORY_MAPPED_ENABLED_PROP);
	}

	@Test
	void configEnablesMemoryMappedTxnStatusFile() throws Exception {
		// ensure legacy system property does not interfere with config-driven setting
		System.setProperty(MEMORY_MAPPED_ENABLED_PROP, "false");

		NativeStoreFactory factory = new NativeStoreFactory();
		NativeStoreConfig config = (NativeStoreConfig) factory.getConfig();

		BNode implNode = SimpleValueFactory.getInstance().createBNode("native-store");
		ModelBuilder builder = new ModelBuilder();
		builder
				.subject(implNode)
				.add(CONFIG.Sail.type, NativeStoreFactory.SAIL_TYPE)
				.add(CONFIG.Native.tripleIndexes, "spoc")
				.add(CONFIG.Native.memoryMappedTxnStatusFile, true);
		config.parse(builder.build(), implNode);

		NativeStore sail = (NativeStore) factory.getSail(config);
		sail.setDataDir(dataDir);
		sail.init();

		try {
			assertThat(getTxnStatusFile(sail)).isInstanceOf(MemoryMappedTxnStatusFile.class);
		} finally {
			sail.shutDown();
		}
	}

	@Test
	void systemPropertyIsIgnored() throws Exception {
		System.setProperty(MEMORY_MAPPED_ENABLED_PROP, "true");

		NativeStoreFactory factory = new NativeStoreFactory();
		NativeStoreConfig config = (NativeStoreConfig) factory.getConfig();
		config.setTripleIndexes("spoc");

		NativeStore sail = (NativeStore) factory.getSail(config);
		sail.setDataDir(dataDir);
		sail.init();

		try {
			assertThat(getTxnStatusFile(sail)).isNotInstanceOf(MemoryMappedTxnStatusFile.class);
		} finally {
			sail.shutDown();
		}
	}

	private Object getTxnStatusFile(NativeStore sail) throws NoSuchFieldException, IllegalAccessException {
		SailStore sailStore = sail.getSailStore();
		NativeSailStore nativeSailStore;
		if (sailStore instanceof SnapshotSailStore) {
			Field backingField = SnapshotSailStore.class.getDeclaredField("backingStore");
			backingField.setAccessible(true);
			nativeSailStore = (NativeSailStore) backingField.get(sailStore);
		} else {
			nativeSailStore = (NativeSailStore) sailStore;
		}

		Field tripleStoreField = NativeSailStore.class.getDeclaredField("tripleStore");
		tripleStoreField.setAccessible(true);
		TripleStore tripleStore = (TripleStore) tripleStoreField.get(nativeSailStore);

		Field txnStatusFileField = TripleStore.class.getDeclaredField("txnStatusFile");
		txnStatusFileField.setAccessible(true);
		return txnStatusFileField.get(tripleStore);
	}
}
