/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.workbench.commands;

import java.io.BufferedWriter;
import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.HttpServletResponse;

import org.eclipse.rdf4j.workbench.base.TransformationServlet;
import org.eclipse.rdf4j.workbench.sailstack.SailStackConfigGenerator;
import org.eclipse.rdf4j.workbench.sailstack.SailStackConfigResult;
import org.eclipse.rdf4j.workbench.sailstack.SailStackSpec;
import org.eclipse.rdf4j.workbench.util.WorkbenchRequest;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;

public class CustomSailPreviewServlet extends TransformationServlet {
	private static final ObjectMapper MAPPER = new ObjectMapper();
	private static final SailStackConfigGenerator GENERATOR = new SailStackConfigGenerator();

	@Override
	protected void service(WorkbenchRequest req, HttpServletResponse resp, String xslPath) throws Exception {
		resp.setContentType("application/json");
		ObjectNode jsonObject = MAPPER.createObjectNode();
		try {
			SailStackSpec spec = readSpec(req);
			SailStackConfigResult result = GENERATOR.generate(spec);
			jsonObject.put("turtle", result.getTurtle());
			jsonObject.set("warnings", MAPPER.valueToTree(result.getValidation().getWarnings()));
			jsonObject.set("errors", MAPPER.valueToTree(result.getValidation().getErrors()));
		} catch (JsonProcessingException e) {
			resp.setStatus(HttpServletResponse.SC_BAD_REQUEST);
			jsonObject.put("turtle", "");
			jsonObject.set("warnings", MAPPER.createArrayNode());
			jsonObject.set("errors", MAPPER.valueToTree(new String[] { "Invalid stack specification." }));
		}
		try (PrintWriter writer = new PrintWriter(new BufferedWriter(resp.getWriter()))) {
			writer.write(MAPPER.writeValueAsString(jsonObject));
		}
	}

	private SailStackSpec readSpec(WorkbenchRequest req) throws IOException {
		String raw = req.getParameter("stackSpec");
		if (raw != null && !raw.isBlank()) {
			return MAPPER.readValue(raw, SailStackSpec.class);
		}
		return MAPPER.readValue(req.getReader(), SailStackSpec.class);
	}
}
