/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.workbench.sailstack;

import java.util.Map;

final class ConfigValueReader {
	private ConfigValueReader() {
	}

	static String readString(Map<String, Object> config, String key) {
		Object value = config.get(key);
		if (value == null) {
			return null;
		}
		return value.toString().trim();
	}

	static String readString(Map<String, Object> config, String key, String defaultValue) {
		String value = readString(config, key);
		return value == null || value.isEmpty() ? defaultValue : value;
	}

	static boolean readBoolean(Map<String, Object> config, String key, boolean defaultValue) {
		Object value = config.get(key);
		if (value == null) {
			return defaultValue;
		}
		if (value instanceof Boolean) {
			return (boolean) value;
		}
		return Boolean.parseBoolean(value.toString());
	}

	static Integer readInt(Map<String, Object> config, String key) {
		Object value = config.get(key);
		if (value == null) {
			return null;
		}
		if (value instanceof Number) {
			return ((Number) value).intValue();
		}
		String text = value.toString().trim();
		if (text.isEmpty()) {
			return null;
		}
		return Integer.parseInt(text);
	}

	static Long readLong(Map<String, Object> config, String key) {
		Object value = config.get(key);
		if (value == null) {
			return null;
		}
		if (value instanceof Number) {
			return ((Number) value).longValue();
		}
		String text = value.toString().trim();
		if (text.isEmpty()) {
			return null;
		}
		return Long.parseLong(text);
	}
}
