/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.workbench.sailstack;

import java.io.StringWriter;

import org.eclipse.rdf4j.model.Model;
import org.eclipse.rdf4j.model.impl.LinkedHashModel;
import org.eclipse.rdf4j.repository.config.RepositoryConfig;
import org.eclipse.rdf4j.repository.sail.config.SailRepositoryConfig;
import org.eclipse.rdf4j.rio.RDFFormat;
import org.eclipse.rdf4j.rio.Rio;
import org.eclipse.rdf4j.rio.WriterConfig;
import org.eclipse.rdf4j.rio.helpers.BasicWriterSettings;
import org.eclipse.rdf4j.sail.config.SailImplConfig;

public class SailStackConfigGenerator {
	private final SailDescriptorRegistry registry = new SailDescriptorRegistry();
	private final SailStackValidator validator = new SailStackValidator();

	public SailStackConfigResult generate(SailStackSpec spec) {
		SailStackValidationResult validation = validator.validate(spec);
		if (validation.hasErrors()) {
			return new SailStackConfigResult(null, "", validation);
		}

		SailImplConfig sailConfig = buildSailConfig(spec, validation);
		RepositoryConfig repositoryConfig = new RepositoryConfig();
		repositoryConfig.setID(spec.getRepo().getId());
		if (spec.getRepo().getTitle() != null && !spec.getRepo().getTitle().isBlank()) {
			repositoryConfig.setTitle(spec.getRepo().getTitle());
		}
		repositoryConfig.setRepositoryImplConfig(new SailRepositoryConfig(sailConfig));
		repositoryConfig.validate();

		String turtle = exportTurtle(repositoryConfig);
		return new SailStackConfigResult(repositoryConfig, turtle, validation);
	}

	private SailImplConfig buildSailConfig(SailStackSpec spec, SailStackValidationResult validation) {
		SailImplConfig delegate = null;
		for (int i = spec.getStack().size() - 1; i >= 0; i--) {
			SailLayerSpec layer = spec.getStack().get(i);
			SailDescriptor descriptor = registry.getDescriptor(layer.getType());
			if (descriptor == null) {
				validation.addError("Unsupported sail type: " + layer.getType());
				continue;
			}
			delegate = descriptor.buildConfig(layer.getConfig(), delegate, validation);
		}
		return delegate;
	}

	private String exportTurtle(RepositoryConfig repositoryConfig) {
		Model model = new LinkedHashModel();
		repositoryConfig.export(model);
		WriterConfig writerConfig = new WriterConfig();
		writerConfig.set(BasicWriterSettings.PRETTY_PRINT, true);
		writerConfig.set(BasicWriterSettings.INLINE_BLANK_NODES, true);
		StringWriter writer = new StringWriter();
		Rio.write(model, writer, RDFFormat.TURTLE, writerConfig);
		return writer.toString();
	}
}
