/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.workbench.sailstack;

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.regex.Pattern;

public class SailStackValidator {
	private static final Pattern REPOSITORY_ID_PATTERN = Pattern.compile("^[a-z0-9._-]+$");

	public SailStackValidationResult validate(SailStackSpec spec) {
		SailStackValidationResult result = new SailStackValidationResult();
		if (spec == null) {
			result.addError("Stack specification is required.");
			return result;
		}

		RepoSpec repo = spec.getRepo();
		if (repo == null || repo.getId() == null || repo.getId().isBlank()) {
			result.addError("Repository ID is required.");
		} else if (!REPOSITORY_ID_PATTERN.matcher(repo.getId()).matches()) {
			result.addWarning("Repository ID contains unsupported characters.");
		}

		List<SailLayerSpec> stack = spec.getStack();
		if (stack == null || stack.isEmpty()) {
			result.addError("Stack must contain exactly one base store.");
			return result;
		}

		Set<SailLayerType> seen = new HashSet<>();
		int baseIndex = -1;
		for (int i = 0; i < stack.size(); i++) {
			SailLayerSpec layer = stack.get(i);
			if (layer == null || layer.getType() == null) {
				result.addError("Each stack layer must specify a type.");
				continue;
			}
			SailLayerType type = layer.getType();
			if (!seen.add(type)) {
				result.addError("Duplicate layer detected: " + type.name());
			}
			if (type.isBase()) {
				if (baseIndex >= 0) {
					result.addError("Exactly one base store is allowed.");
				}
				baseIndex = i;
			}
			if (type == SailLayerType.LUCENE) {
				String indexDir = ConfigValueReader.readString(layer.getConfig(), "indexDir");
				if (indexDir == null || indexDir.isBlank()) {
					result.addError("Lucene index directory is required.");
				}
			}
			validateNumbers(layer, result);
		}

		if (baseIndex < 0) {
			result.addError("Stack must include a base store.");
		} else if (baseIndex != stack.size() - 1) {
			result.addError("Base store must be the bottommost layer.");
		}

		if (baseIndex >= 0) {
			for (int i = baseIndex + 1; i < stack.size(); i++) {
				SailLayerSpec layer = stack.get(i);
				if (layer != null && layer.getType() != null && layer.getType().isWrapper()) {
					result.addError("Wrappers must appear above the base store.");
				}
			}
		}

		addOrderingWarnings(stack, result);
		return result;
	}

	private void validateNumbers(SailLayerSpec layer, SailStackValidationResult result) {
		if (layer.getConfig() == null) {
			return;
		}
		validateLong(layer, result, "syncDelay");
		validateLong(layer, result, "iterationCacheSyncThreshold");
		validateInt(layer, result, "valueCacheSize");
		validateInt(layer, result, "valueIDCacheSize");
		validateInt(layer, result, "namespaceCacheSize");
		validateInt(layer, result, "namespaceIDCacheSize");
		validateLong(layer, result, "tripleDBSize");
		validateLong(layer, result, "valueDBSize");
		validateLong(layer, result, "valueEvictionInterval");
		validateLong(layer, result, "validationResultsLimitTotal");
		validateLong(layer, result, "validationResultsLimitPerConstraint");
	}

	private void validateLong(SailLayerSpec layer, SailStackValidationResult result, String key) {
		try {
			ConfigValueReader.readLong(layer.getConfig(), key);
		} catch (NumberFormatException e) {
			result.addError("Expected numeric value for " + key + " in " + layer.getType());
		}
	}

	private void validateInt(SailLayerSpec layer, SailStackValidationResult result, String key) {
		try {
			ConfigValueReader.readInt(layer.getConfig(), key);
		} catch (NumberFormatException e) {
			result.addError("Expected numeric value for " + key + " in " + layer.getType());
		}
	}

	private void addOrderingWarnings(List<SailLayerSpec> stack, SailStackValidationResult result) {
		int luceneIndex = indexOf(stack, SailLayerType.LUCENE);
		int rdfsIndex = indexOf(stack, SailLayerType.RDFS);
		if (luceneIndex >= 0 && rdfsIndex >= 0 && luceneIndex < rdfsIndex) {
			result.addWarning("Put RDFS above Lucene if you want inferred literals searchable.");
		}
		int shaclIndex = indexOf(stack, SailLayerType.SHACL);
		if (shaclIndex >= 0 && rdfsIndex >= 0) {
			if (shaclIndex < rdfsIndex) {
				result.addWarning("SHACL above RDFS validates explicit data only.");
			} else {
				result.addWarning("RDFS above SHACL validates inferred-augmented data.");
			}
		}
	}

	private int indexOf(List<SailLayerSpec> stack, SailLayerType type) {
		if (stack == null) {
			return -1;
		}
		for (int i = 0; i < stack.size(); i++) {
			SailLayerSpec layer = stack.get(i);
			if (layer != null && type == layer.getType()) {
				return i;
			}
		}
		return -1;
	}
}
