/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.workbench.sailstack;

import java.util.LinkedHashMap;
import java.util.Map;

import org.eclipse.rdf4j.common.transaction.QueryEvaluationMode;
import org.eclipse.rdf4j.sail.base.config.BaseSailConfig;
import org.eclipse.rdf4j.sail.config.AbstractSailImplConfig;
import org.eclipse.rdf4j.sail.config.SailImplConfig;
import org.eclipse.rdf4j.sail.inferencer.fc.config.SchemaCachingRDFSInferencerConfig;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.eclipse.rdf4j.sail.lucene.impl.config.LuceneSailConfig;
import org.eclipse.rdf4j.sail.memory.config.MemoryStoreConfig;
import org.eclipse.rdf4j.sail.nativerdf.config.NativeStoreConfig;
import org.eclipse.rdf4j.sail.shacl.config.ShaclSailConfig;

public class SailDescriptorRegistry {
	private final Map<SailLayerType, SailDescriptor> descriptors = new LinkedHashMap<>();

	public SailDescriptorRegistry() {
		descriptors.put(SailLayerType.MEMORY, new MemoryDescriptor());
		descriptors.put(SailLayerType.NATIVE, new NativeDescriptor());
		descriptors.put(SailLayerType.LMDB, new LmdbDescriptor());
		descriptors.put(SailLayerType.RDFS, new RdfsDescriptor());
		descriptors.put(SailLayerType.SHACL, new ShaclDescriptor());
		descriptors.put(SailLayerType.LUCENE, new LuceneDescriptor());
	}

	public SailDescriptor getDescriptor(SailLayerType type) {
		return descriptors.get(type);
	}

	private static void applyCommonBaseConfig(AbstractSailImplConfig config, Map<String, Object> options,
			SailStackValidationResult validation) {
		Long threshold = ConfigValueReader.readLong(options, "iterationCacheSyncThreshold");
		if (threshold != null) {
			config.setIterationCacheSyncThreshold(threshold);
		}
		String mode = ConfigValueReader.readString(options, "defaultQueryEvaluationMode");
		if (mode != null && !mode.isBlank() && config instanceof BaseSailConfig) {
			try {
				QueryEvaluationMode evaluationMode = QueryEvaluationMode.valueOf(mode.toUpperCase());
				((BaseSailConfig) config).setDefaultQueryEvaluationMode(evaluationMode);
			} catch (IllegalArgumentException e) {
				validation.addError("Unknown query evaluation mode: " + mode);
			}
		}
	}

	private static final class MemoryDescriptor implements SailDescriptor {
		@Override
		public SailLayerType getType() {
			return SailLayerType.MEMORY;
		}

		@Override
		public String getDisplayName() {
			return "Memory Store";
		}

		@Override
		public SailImplConfig buildConfig(Map<String, Object> config, SailImplConfig delegate,
				SailStackValidationResult validation) {
			MemoryStoreConfig memory = new MemoryStoreConfig();
			memory.setPersist(ConfigValueReader.readBoolean(config, "persist", true));
			Long syncDelay = ConfigValueReader.readLong(config, "syncDelay");
			if (syncDelay != null) {
				memory.setSyncDelay(syncDelay);
			}
			applyCommonBaseConfig(memory, config, validation);
			return memory;
		}
	}

	private static final class NativeDescriptor implements SailDescriptor {
		@Override
		public SailLayerType getType() {
			return SailLayerType.NATIVE;
		}

		@Override
		public String getDisplayName() {
			return "Native Store";
		}

		@Override
		public SailImplConfig buildConfig(Map<String, Object> config, SailImplConfig delegate,
				SailStackValidationResult validation) {
			NativeStoreConfig nativeConfig = new NativeStoreConfig();
			nativeConfig.setTripleIndexes(ConfigValueReader.readString(config, "tripleIndexes", "spoc,posc"));
			nativeConfig.setForceSync(ConfigValueReader.readBoolean(config, "forceSync", false));
			Integer valueCacheSize = ConfigValueReader.readInt(config, "valueCacheSize");
			if (valueCacheSize != null) {
				nativeConfig.setValueCacheSize(valueCacheSize);
			}
			Integer valueIdCacheSize = ConfigValueReader.readInt(config, "valueIDCacheSize");
			if (valueIdCacheSize != null) {
				nativeConfig.setValueIDCacheSize(valueIdCacheSize);
			}
			Integer namespaceCacheSize = ConfigValueReader.readInt(config, "namespaceCacheSize");
			if (namespaceCacheSize != null) {
				nativeConfig.setNamespaceCacheSize(namespaceCacheSize);
			}
			Integer namespaceIdCacheSize = ConfigValueReader.readInt(config, "namespaceIDCacheSize");
			if (namespaceIdCacheSize != null) {
				nativeConfig.setNamespaceIDCacheSize(namespaceIdCacheSize);
			}
			applyCommonBaseConfig(nativeConfig, config, validation);
			return nativeConfig;
		}
	}

	private static final class LmdbDescriptor implements SailDescriptor {
		@Override
		public SailLayerType getType() {
			return SailLayerType.LMDB;
		}

		@Override
		public String getDisplayName() {
			return "LMDB Store";
		}

		@Override
		public SailImplConfig buildConfig(Map<String, Object> config, SailImplConfig delegate,
				SailStackValidationResult validation) {
			LmdbStoreConfig lmdb = new LmdbStoreConfig();
			lmdb.setTripleIndexes(ConfigValueReader.readString(config, "tripleIndexes", "spoc,posc"));
			Long tripleDbSize = ConfigValueReader.readLong(config, "tripleDBSize");
			if (tripleDbSize != null) {
				lmdb.setTripleDBSize(tripleDbSize);
			}
			Long valueDbSize = ConfigValueReader.readLong(config, "valueDBSize");
			if (valueDbSize != null) {
				lmdb.setValueDBSize(valueDbSize);
			}
			lmdb.setForceSync(ConfigValueReader.readBoolean(config, "forceSync", false));
			lmdb.setAutoGrow(ConfigValueReader.readBoolean(config, "autoGrow", true));
			Integer valueCacheSize = ConfigValueReader.readInt(config, "valueCacheSize");
			if (valueCacheSize != null) {
				lmdb.setValueCacheSize(valueCacheSize);
			}
			Integer valueIdCacheSize = ConfigValueReader.readInt(config, "valueIDCacheSize");
			if (valueIdCacheSize != null) {
				lmdb.setValueIDCacheSize(valueIdCacheSize);
			}
			Integer namespaceCacheSize = ConfigValueReader.readInt(config, "namespaceCacheSize");
			if (namespaceCacheSize != null) {
				lmdb.setNamespaceCacheSize(namespaceCacheSize);
			}
			Integer namespaceIdCacheSize = ConfigValueReader.readInt(config, "namespaceIDCacheSize");
			if (namespaceIdCacheSize != null) {
				lmdb.setNamespaceIDCacheSize(namespaceIdCacheSize);
			}
			Long valueEvictionInterval = ConfigValueReader.readLong(config, "valueEvictionInterval");
			if (valueEvictionInterval != null) {
				lmdb.setValueEvictionInterval(valueEvictionInterval);
			}
			applyCommonBaseConfig(lmdb, config, validation);
			return lmdb;
		}
	}

	private static final class RdfsDescriptor implements SailDescriptor {
		@Override
		public SailLayerType getType() {
			return SailLayerType.RDFS;
		}

		@Override
		public String getDisplayName() {
			return "Schema-caching RDFS inferencer";
		}

		@Override
		public SailImplConfig buildConfig(Map<String, Object> config, SailImplConfig delegate,
				SailStackValidationResult validation) {
			return new SchemaCachingRDFSInferencerConfig(delegate);
		}
	}

	private static final class ShaclDescriptor implements SailDescriptor {
		@Override
		public SailLayerType getType() {
			return SailLayerType.SHACL;
		}

		@Override
		public String getDisplayName() {
			return "SHACL Sail";
		}

		@Override
		public SailImplConfig buildConfig(Map<String, Object> config, SailImplConfig delegate,
				SailStackValidationResult validation) {
			ShaclSailConfig shacl = new ShaclSailConfig(delegate);
			shacl.setValidationEnabled(ConfigValueReader.readBoolean(config, "validationEnabled", true));
			shacl.setParallelValidation(ConfigValueReader.readBoolean(config, "parallelValidation", true));
			shacl.setRdfsSubClassReasoning(ConfigValueReader.readBoolean(config, "rdfsSubClassReasoning", true));
			Long totalLimit = ConfigValueReader.readLong(config, "validationResultsLimitTotal");
			if (totalLimit != null) {
				shacl.setValidationResultsLimitTotal(totalLimit);
			}
			Long perConstraintLimit = ConfigValueReader.readLong(config, "validationResultsLimitPerConstraint");
			if (perConstraintLimit != null) {
				shacl.setValidationResultsLimitPerConstraint(perConstraintLimit);
			}
			return shacl;
		}
	}

	private static final class LuceneDescriptor implements SailDescriptor {
		@Override
		public SailLayerType getType() {
			return SailLayerType.LUCENE;
		}

		@Override
		public String getDisplayName() {
			return "Lucene Sail";
		}

		@Override
		public SailImplConfig buildConfig(Map<String, Object> config, SailImplConfig delegate,
				SailStackValidationResult validation) {
			String indexDir = ConfigValueReader.readString(config, "indexDir");
			if (indexDir == null || indexDir.isBlank()) {
				validation.addError("Lucene index directory is required.");
				indexDir = "lucene";
			}
			LuceneSailConfig lucene = new LuceneSailConfig(indexDir, delegate);
			return lucene;
		}
	}
}
