/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.workbench.sailstack;

import org.eclipse.rdf4j.repository.config.RepositoryConfig;

public class SailStackConfigResult {
	private final RepositoryConfig repositoryConfig;
	private final String turtle;
	private final SailStackValidationResult validation;

	public SailStackConfigResult(RepositoryConfig repositoryConfig, String turtle,
			SailStackValidationResult validation) {
		this.repositoryConfig = repositoryConfig;
		this.turtle = turtle;
		this.validation = validation;
	}

	public RepositoryConfig getRepositoryConfig() {
		return repositoryConfig;
	}

	public String getTurtle() {
		return turtle;
	}

	public SailStackValidationResult getValidation() {
		return validation;
	}
}
