/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.workbench.sailstack;

public enum SailLayerType {
	MEMORY(true),
	NATIVE(true),
	LMDB(true),
	RDFS(false),
	SHACL(false),
	LUCENE(false);

	private final boolean base;

	SailLayerType(boolean base) {
		this.base = base;
	}

	public boolean isBase() {
		return base;
	}

	public boolean isWrapper() {
		return !base;
	}
}
