/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.workbench.sailstack;

import java.util.ArrayList;
import java.util.List;

public class SailStackSpec {
	private RepoSpec repo = new RepoSpec();
	private List<SailLayerSpec> stack = new ArrayList<>();

	public RepoSpec getRepo() {
		return repo;
	}

	public void setRepo(RepoSpec repo) {
		this.repo = repo == null ? new RepoSpec() : repo;
	}

	public List<SailLayerSpec> getStack() {
		return stack;
	}

	public void setStack(List<SailLayerSpec> stack) {
		this.stack = stack == null ? new ArrayList<>() : new ArrayList<>(stack);
	}
}
