/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.workbench.sailstack;

import java.util.LinkedHashMap;
import java.util.Map;

public class SailLayerSpec {
	private SailLayerType type;
	private Map<String, Object> config = new LinkedHashMap<>();

	public SailLayerType getType() {
		return type;
	}

	public void setType(SailLayerType type) {
		this.type = type;
	}

	public Map<String, Object> getConfig() {
		return config;
	}

	public void setConfig(Map<String, Object> config) {
		this.config = config == null ? new LinkedHashMap<>() : new LinkedHashMap<>(config);
	}
}
