/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.workbench.sailstack;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class SailStackValidationResult {
	private final List<String> errors = new ArrayList<>();
	private final List<String> warnings = new ArrayList<>();

	public void addError(String message) {
		if (message != null && !message.isBlank()) {
			errors.add(message);
		}
	}

	public void addWarning(String message) {
		if (message != null && !message.isBlank()) {
			warnings.add(message);
		}
	}

	public List<String> getErrors() {
		return Collections.unmodifiableList(errors);
	}

	public List<String> getWarnings() {
		return Collections.unmodifiableList(warnings);
	}

	public boolean hasErrors() {
		return !errors.isEmpty();
	}
}
